/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.inacap.bibliotecaApp.vista;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Corvalan
 */
public class TrabajadorTelefonosFrame extends javax.swing.JFrame {

    /**
     * Creates new form TrabajadorTelefonosFrame
     */
    public TrabajadorTelefonosFrame() {
        initComponents();
        setIconImage(getIconImage());
        this.setLocationRelativeTo(null);
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icono_img.png"));
        return retValue;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        fono_3_txt = new javax.swing.JTextField();
        fono_1_txt = new javax.swing.JTextField();
        fono_2_txt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        actualizar_fono_btn = new javax.swing.JButton();
        editar_fono_btn = new javax.swing.JButton();
        listar_fono_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaFono = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Trabajador - Telefonos");

        jPanelPrincipal.setBackground(new java.awt.Color(51, 51, 51));
        jPanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(39, 151, 212));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fono_3_txt.setBackground(java.awt.SystemColor.controlLtHighlight);
        jPanel2.add(fono_3_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 180, 35));

        fono_1_txt.setBackground(java.awt.SystemColor.controlLtHighlight);
        jPanel2.add(fono_1_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 180, 35));

        fono_2_txt.setBackground(java.awt.SystemColor.controlLtHighlight);
        jPanel2.add(fono_2_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 180, 35));

        jLabel16.setBackground(new java.awt.Color(102, 102, 102));
        jLabel16.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Telefono 1");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 30));

        jLabel17.setBackground(new java.awt.Color(102, 102, 102));
        jLabel17.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Telefono 2");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 30));

        jLabel18.setBackground(new java.awt.Color(102, 102, 102));
        jLabel18.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Telefono 3");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, 30));

        jLabel19.setBackground(new java.awt.Color(102, 102, 102));
        jLabel19.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Datos - Telefono");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, 30));

        jLabel15.setBackground(new java.awt.Color(102, 102, 102));
        jLabel15.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/telefono.png"))); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 50, 50));

        actualizar_fono_btn.setBackground(new java.awt.Color(255, 255, 255));
        actualizar_fono_btn.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 13)); // NOI18N
        actualizar_fono_btn.setForeground(new java.awt.Color(0, 0, 0));
        actualizar_fono_btn.setText("Actualizar");
        actualizar_fono_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizar_fono_btnActionPerformed(evt);
            }
        });
        jPanel2.add(actualizar_fono_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 100, 30));

        jPanelPrincipal.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 450));

        editar_fono_btn.setBackground(new java.awt.Color(255, 255, 255));
        editar_fono_btn.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 13)); // NOI18N
        editar_fono_btn.setForeground(new java.awt.Color(0, 0, 0));
        editar_fono_btn.setText("Editar");
        editar_fono_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editar_fono_btnActionPerformed(evt);
            }
        });
        jPanelPrincipal.add(editar_fono_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 150, 30));

        listar_fono_btn.setBackground(new java.awt.Color(255, 255, 255));
        listar_fono_btn.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 13)); // NOI18N
        listar_fono_btn.setForeground(new java.awt.Color(0, 0, 0));
        listar_fono_btn.setText("Listar");
        listar_fono_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listar_fono_btnActionPerformed(evt);
            }
        });
        jPanelPrincipal.add(listar_fono_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 150, 30));

        tablaFono.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Telefono 1", "Telefono 2", "Telefono 3"
            }
        ));
        jScrollPane1.setViewportView(tablaFono);

        jPanelPrincipal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 330, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editar_fono_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editar_fono_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editar_fono_btnActionPerformed

    private void listar_fono_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listar_fono_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listar_fono_btnActionPerformed

    private void actualizar_fono_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizar_fono_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actualizar_fono_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrabajadorTelefonosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrabajadorTelefonosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrabajadorTelefonosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrabajadorTelefonosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrabajadorTelefonosFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton actualizar_fono_btn;
    public javax.swing.JButton editar_fono_btn;
    public javax.swing.JTextField fono_1_txt;
    public javax.swing.JTextField fono_2_txt;
    public javax.swing.JTextField fono_3_txt;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton listar_fono_btn;
    public javax.swing.JTable tablaFono;
    // End of variables declaration//GEN-END:variables
}
